FORMAT: 1A
HOST: http://185.26.115.63

# SalesFor.Me

Версия 1.0

Все методы доступа к API доступны с префиксом /api/v1/

# Group Информационные методы

## Получение основных данных системы [/info]

### Запрос данных [GET]

+ Response 200 (application/json)

    + Body
    
            {
                "version": "1.0.0",
                "description": "API SalesForMe",
                "vk_app": 5222884,
                "vk_api_version": "5.52",
                "fb_app": 152750598427241,
                "google_app": "799617381412-qg9dbdsmtfr0aiui4o11btj0a368l3gh.apps.googleusercontent.com",
                "mailru_app": 746248
            }

# Group Авторизация пользователя

## Прямая авторизация пользователя [/auth]

### Запрос авторизации [POST]

+ Request (x-www-form-urlencoded)

            "email": "test@salesfor.me",
            "password": "userpassword",

+ Request (application/json)

    + Body

            {
                "email": "testuser",
                "password": "userpassword"
            }

+ Response 200 (application/json)

  + Body

            {
                "meta": { },
                "result": {
                    "sid": "c354b133-b7cb-4aab-949e-a669e68b9c0d.1469648474933.51a4824a1fdc629a3f30886290d26828b036edb6",
                    "auth": {
                        "uuid": "c354b133-b7cb-4aab-949e-a669e68b9c0d"
                    }
                }
            }


## Авторизация через соцсети [/auth?id=:id&code=:code&redirect_uri=:redirect_uri]

+ Parameters
    
    + id -- string, social network name (fb, vk)
    + code -- string, authorization code
    + redirect_uri -- тот же URL, который был указан в строке запроса авторизации 
    соцсети при прохождении процедуры OAuth2 авторизации

### Запрос авторизации [GET]

Описание ответа системы:

+ `sid` -- идентификатор сессии пользователя, используется в заголовке `x-session-id` 
+ `auth`:
    + `uuid` -- пользовательский уникальный номер в системе
    + `access_data` -- авторизационные данные соцсети

+ Response 200 (application/json)

    + Body

            {
                "meta": {},
                "result": {
                    "sid": "0ab372c9-2d4b-4c47-8373-b764d92c6092.1469648167592.0e7dbffba0fabce18341e1ce407c452b7d33567d",
                    "auth": {
                        "uuid": "0ab372c9-2d4b-4c47-8373-b764d92c6092",
                        "access_data": {
                            "access_token": "ya29.CjAtA-dWSM-80aOnvwa96zvfUBHdHn7p8oJuHCU4-ew6PVPyQrr2zSeMAEv-VKCGT5A",
                            "token_type": "Bearer",
                            "expires_in": 3599,
                            "id_token": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjUwNzgyYmNmMGE5NzQxZTZiZjkwMjY2ZGMzNTY4YWE5MDc5MWYxNmYifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhdF9oYXNoIjoiVkV4eHVxc0FSbG4zQ3RCNkFaM0NjQSIsImF1ZCI6Ijc5OTYxNzM4MTQxMi1xZzlkYmRzbXRmcjBhaXVpNG8xMWJ0ajBhMzY4bDNnaC5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsInN1YiI6IjEwNDAyNTY0MzY2MzI1MTM3NjQ3NCIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhenAiOiI3OTk2MTczODE0MTItcWc5ZGJkc210ZnIwYWl1aTRvMTFidGowYTM2OGwzZ2guYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJoZCI6IjY1YXBwcy5jb20iLCJlbWFpbCI6ImFiYWJraW5ANjVhcHBzLmNvbSIsImlhdCI6MTQ2OTY0ODE2NywiZXhwIjoxNDY5NjUxNzY3fQ.RnvEDNe6k5ttX00I2bbFbT3ZilaPu3ZqqBXIKTLj7WaFx7Alw6W4yZO_FGTYDxCedr0O0nOg6xh5J4buPK26Pbt57XnZqyYMEucHUjuXz3VOFOIRb_lqTAW5YOM7TvylHJF_mMIzH5HjXVgkdj8Jdtl29-J3q-sFhMmHzm45EPKPp9kwnO4eVK1mhLk7YmmQP8dwSFi-a-0Ti8LZNMm7fPEw9AvXujwcrLIPjZVOmC_udrAcUNWaz46QrHtsB3c9dX-kyjkfvS3MZ9xwTlLyglvx6LxI2iBK1etl6Pt5cXxaEM-wAFE4mteDLFtXxaO6yCcHnOKW2nRt7roWZ-Z6PA"
                        }
                    }
                }
            }
            
# Group Cущности системы            

## Пользователи системы [/users]

## Текущий пользователь системы [/users/me]

### Получение данных [GET]

+ Request

    + Headers

            X-Session-Id: c354b133-b7cb-4aab-949e-a669e68b9c0d.1470060821891.e92ea61b90ba93533a49f0a30f7ea18ffabd9532

+ Response 200 (application/json)

    + Body

            {
                "meta": { },
                "result": {
                    "uuid": "c354b133-b7cb-4aab-949e-a669e68b9c0d",
                    "created": "2016-07-22T19:03:24.187Z",
                    "first_name": "Иван",
                    "last_name": "Табуреткин",
                    "regs": [
                        {
                            "user": "c354b133-b7cb-4aab-949e-a669e68b9c0d",
                            "type": "VK",
                            "email": "test@test.com",
                            "user_id": "7450050",
                            "created": "2016-07-22T19:03:24.281Z",
                            "authorized": "2016-08-01T14:13:41.885Z"
                        },
                        {
                            "user": "c354b133-b7cb-4aab-949e-a669e68b9c0d",
                            "type": "native",
                            "email": "ab@izh.com",
                            "user_id": "test@test.com",
                            "created": "2016-07-25T19:02:44.337Z",
                            "authorized": "2016-07-25T19:41:54.882Z"
                        }
                    ]
                }
            }

### Изменение своих данных [PUT]

+ Request

    + Headers

            X-Session-Id: c354b133-b7cb-4aab-949e-a669e68b9c0d.1470060821891.e92ea61b90ba93533a49f0a30f7ea18ffabd9532
    + Body

            {
                "first_name": "Иван",
                "last_name": "Табуреткин",
                "password": "12345"
            }

+ Response 200 (application/json)

    + Body

            {
                "meta": { },
                "result": "ok"
            }

## Магазины [/shops]

### Получение списка магазинов [GET]

Получение фильтруемого и сортируемого списка магазинов

+ Response 200 (application/json)

    + Body

            {
                "meta": {
                    "total": 2
                },
                "result": [
                    {
                        "uuid": "d321be07-a592-4379-98f7-bf5f6d1fefab",
                        "title": "ООО \"Бюро вечных услуг\"",
                        "phone": "89125554433",
                        "address": "РФ, г.Казань, пр. Амирхана, д. 22",
                        "href": "http://bes.ru",
                        "latitude": 512346,
                        "longitude": 501456,
                        "accuracy": 10
                    }
                ]
            }

### Публикация данных нового магазина [POST]           

+ Request (application/json)

    + Headers

            X-Session-Id: c354b133-b7cb-4aab-949e-a669e68b9c0d.1470060821891.e92ea61b90ba93533a49f0a30f7ea18ffabd9532

    + Body 

            {
                "title": "ООО \"Бюро вечных услуг\"",
                "phone": "89125554433",
                "address": "РФ, г.Казань, пр. Амирхана, д. 22",
                "href": "http://bes.ru",
                "latitude": 512346,
                "longitude": 501456,
                "accuracy": 10
            }

+ Response 200 (application/json)

    + Body

            {
                "meta": { },
                "result": "d321be07-a592-4379-98f7-bf5f6d1fefab"    
            }

## Акции [/actions]

### Получение списка акций [GET]

Получение фильтруемого и сортируемого списка акций

+ Response 200 (application/json)

    + Body

            {

                "meta": {
                    "total": 1
                },
                "result": [
                    {
                        "uuid": "62750aae-c367-4f35-b9cf-a49aa9bbcb52",
                        "title": "Первая акция",
                        "category": "мода",
                        "cat2gis": null,
                        "description": "это самая первая акция, добавленная в сисстему для теста",
                        "discount_value": 20,
                        "discount_min": 20,
                        "discount_max": 30,
                        "expiration_begin": "2016-08-01T00:00:00.000Z",
                        "expiration_end": "2016-08-07T00:00:00.000Z",
                        "shop": "d321be07-a592-4379-98f7-bf5f6d1fefab",
                        "expiration_interval": {
                            "days": 6
                        },
                        "rating": 4
                    }
                ]
            }

### Публикация новой акции [POST]           

+ Request (application/json)

    + Headers

            X-Session-Id: c354b133-b7cb-4aab-949e-a669e68b9c0d.1470060821891.e92ea61b90ba93533a49f0a30f7ea18ffabd9532

    + Body 

            {
                "title": "Первая акция",
                "category": "мода",
                "description": "это самая первая акция, добавленная в сисстему для теста",
                "discount_value": 20,
                "discount_min": 20,
                "discount_max": 30,
                "expiration_begin": "2016-08-01T00:00:00.000Z",
                "expiration_end": "2016-08-07T00:00:00.000Z",
                "shop": "d321be07-a592-4379-98f7-bf5f6d1fefab"
            }

+ Response 200 (application/json)

    + Body

            {
                "meta": { },
                "result": "c354b133-b7cb-4aab-949e-a669e68b9c0d"    
            }

## Конкретная акция [/actions/{uuid}]

### Получение данных акции [GET]

+ Response 200 (application/json)

    + Body

            {
                "meta": { },
                "result": {
                    "uuid": "62750aae-c367-4f35-b9cf-a49aa9bbcb52",
                    "title": "Первая акция",
                    "category": "мода",
                    "cat2gis": null,
                    "description": "это самая первая акция, добавленная в сисстему для теста",
                    "discount_value": 20,
                    "discount_min": 20,
                    "discount_max": 30,
                    "expiration_begin": "2016-08-01T00:00:00.000Z",
                    "expiration_end": "2016-08-07T00:00:00.000Z",
                    "expiration_interval": {
                        "days": 6
                    },
                    "shop": {
                        "uuid": "d321be07-a592-4379-98f7-bf5f6d1fefab",
                        "title": "ООО \"Бюро вечных услуг\"",
                        "phone": "89125554433",
                        "address": "РФ, г.Казань, пр. Амирхана, д. 22",
                        "href": "http://bes.ru",
                        "latitude": 567123,
                        "longitude": 512354,
                        "accuracy": 10
                    },
                    "images": [
                        "0e4ffced-b242-4eae-bea2-04f10eefd756"
                    ]
                    "rating": "4"
                }   
            }

## Список оценок акции [/actions/{uuid}/rating]

### Получение списка оценок акции [GET]

+ Response 200 (application/json)

    + Body

            {
                "meta": { 
                    "total": 1
                },
                "result": [
                    "timestamp": "2016-08-01T00:00:00.000Z",
                    "rating": 4,
                    "comment": "очень понравилось",
                    "user": "c354b133-b7cb-4aab-949e-a669e68b9c0d"
                ]
            }

### Запись значения рейтинга для акции [PUT]

+ Request (application/json)

    + Headers

            X-Session-Id: c354b133-b7cb-4aab-949e-a669e68b9c0d.1470060821891.e92ea61b90ba93533a49f0a30f7ea18ffabd9532

    + Body 

            {
                "rating": 5,
                "comment": "всё хорошо"
            }

+ Response 200 (application/json)

    + Body

            {
                "meta": {},
                "result": "ok"
            }

## Список изображений акции [/actions/{uuid}/images]

### Получение списка оценок акции [GET]

+ Response 200 (application/json)

    + Body

            {
                "meta": { 
                    "total": 1
                },
                "result": [
                    "0e4ffced-b242-4eae-bea2-04f10eefd756"
                ]
            }

### Добавление изображений к акции [PUT]

+ Request (application/json)

    + Headers

            X-Session-Id: c354b133-b7cb-4aab-949e-a669e68b9c0d.1470060821891.e92ea61b90ba93533a49f0a30f7ea18ffabd9532

    + Body 

            [
                "0e4ffced-b242-4eae-bea2-04f10eefd756"
            ]

+ Response 200 (application/json)

    + Body

            {
                "meta": {},
                "result": "ok"
            }

## Загрузки [/api/uploads]

### Загрузка новых файлов [POST]

+ Request (multipart/form-data, boundary=AaB03x)

    + Body
            
            --AaB03x
            content-disposition: form-data; name="image"
            
            $report
            --AaB03x
            content-disposition: form-data; name="userfile"; filename="$filename"
            Content-Type: $mimetype
            Content-Transfer-Encoding: binary
            
            $binarydata
            --AaB03x--

+ Response 200 (application/json)

        { 
            "meta": {
                "total": 1
            },
            "result": [
                "a7fb7421-5bc0-4e3c-b684-e78b6d7f5ebe"
            ]
        }

## Загруженный файл [/api/uploads/{uuid}]

+ Parameters
    
    + uuid (uuid) -- уникальный идентификатор файла

### Получение файла [GET]

+ Response 200 ($mimetype)

## Информация о загруженном файле [/api/uploads/{uuid}/info]

+ Parameters 
    
    + uuid (uuid) -- уникальный идентификатор файла

### Получение информации [GET]

+ Response 200 (application/json)

        { 
            "meta": { },
            "result": { 
                "uuid": "a7fb7421-5bc0-4e3c-b684-e78b6d7f5ebe",
                "subject": "fc75e5b5-6da3-41f8-934f-43a08de2a380",
                "filename": "b89fe229d25d2edbf9a757d87968f68e",
                "originalname": "uploads.js",
                "mimetype": "application/javascript",
                "destination": "/srv/uploads",
                "size": 2119,
                "timestamp": "2016-08-01T09:13:10.795Z",
                "fieldname": "document" 
            } 
        }

# Group Банерная система

## Зарегистрированные в системе банеры [/banners]

В случае, если запрос на получения списка банеров выполняется с указанием 
заголовка авторизованного пользователя, то будет показан список всех банеров,
а не только активных в текущий промежуток времени.
Это же касается получения информации по конкретному банеру.

"type" банера указывается произвольно для условного определения его назначения и 
указания типа размещения на сайте.

### Получение списка банеров [GET]

+ Response 200 (application/json)

        {
            "meta": {
                "total": 2
            },
            "result": [
                {
                    "uuid": "6d9a662c-0eb6-4c9c-b19f-41f00ef2ddff",
                    "image": "a1b1ed23-5474-4924-854b-232e24bf8ba2",
                    "type": "topBanner",
                    "start_time": "2016-09-13T00:00:00.000Z",
                    "end_time": "2016-09-16T23:59:59.999Z",
                    "description": "",
                    "link": "https://twitter.com/",
                    "views": "0",
                    "transitions": "0",
                    "code": "970a1034570100006d9a662c0eb64c9cb19f41f00ef2ddff35030bf8b1543e95b84d40e24e5c56c4c34546f7"
                },
                {
                    "uuid": "752d44b5-3615-4dd3-85a6-737c312c8fae",
                    "image": "a1b1ed23-5474-4924-854b-232e24bf8ba2",
                    "type": "topBanner",
                    "start_time": "2016-09-13T00:00:00.000Z",
                    "end_time": "2016-09-16T23:59:59.999Z",
                    "description": "",
                    "link": "https://twitter.com/",
                    "views": "1",
                    "transitions": "1",
                    "code": "980a103457010000752d44b536154dd385a6737c312c8fae520d35d9f8d4932caa64aa640d301bcf3b921d6a"
                }
            ]
        }

### Размещение банера [POST]

+ Request (application/json)

    + Headers

            X-Session-Id: c354b133-b7cb-4aab-949e-a669e68b9c0d.1470060821891.e92ea61b90ba93533a49f0a30f7ea18ffabd9532

    + Body

            {
                "image": "a1b1ed23-5474-4924-854b-232e24bf8ba2",
                "type": "topBanner",
                "start_time": "2016-09-13T00:00:00.000Z",
                "end_time": "2016-09-16T23:59:59.999Z",
                "description": "",
                "link": "https://twitter.com/"
            }

+ Response 200 (application/json)

        {
            "meta": {},
            "result": "6d9a662c-0eb6-4c9c-b19f-41f00ef2ddff"
        }


## Данные указанного банера [/banners/:id]

### Получение информации банера [GET]

+ Response 200 (application/json)

        {
            "meta": {},
            "result": {
                "uuid": "6d9a662c-0eb6-4c9c-b19f-41f00ef2ddff",
                "image": "a1b1ed23-5474-4924-854b-232e24bf8ba2",
                "type": "topBanner",
                "start_time": "2016-09-13T00:00:00.000Z",
                "end_time": "2016-09-16T23:59:59.999Z",
                "description": "",
                "link": "https://twitter.com/",
                "views": "0",
                "transitions": "0",
                "code": "970a1034570100006d9a662c0eb64c9cb19f41f00ef2ddff35030bf8b1543e95b84d40e24e5c56c4c34546f7"
            }
        }

### Изменение информации банера [PUT]

+ Request (application/json)

    + Headers

            X-Session-Id: c354b133-b7cb-4aab-949e-a669e68b9c0d.1470060821891.e92ea61b90ba93533a49f0a30f7ea18ffabd9532

    + Body

            {
                "image": "a1b1ed23-5474-4924-854b-232e24bf8ba2",
                "type": "topBanner",
                "start_time": "2016-09-13T00:00:00.000Z",
                "end_time": "2016-09-16T23:59:59.999Z",
                "description": "",
                "link": "https://twitter.com/"
            }

+ Response 200 (application/json)

        {
            "meta": {},
            "result": "ok"
        }

### Удаление банера [DELETE]

+ Request

    + Headers

            X-Session-Id: c354b133-b7cb-4aab-949e-a669e68b9c0d.1470060821891.e92ea61b90ba93533a49f0a30f7ea18ffabd9532

+ Response 200 (application/json)

        {
            "meta": {},
            "result": "ok"
        }

## Отображение рекламного банера [/ads/:code/view]

Данные о просмотрах (views) и переходах по ссылкам банера (transitions)
фиксируются только для одного действия по уникальной ссылке для исключения накрутки.

code -- подставляется из информации о банере

### Получение изображения [GET]

+ Response 200 ($mimetype)

## Ссылка для перехода по рекламе [/ads/:code]

### Переход по рекламе [GET]

+ Response 200 (plain/text)

    + Headers

            Location: $transition_link