FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# SalesFor.Me

Версия 1.0

Все методы доступа к API доступны с префиксом /api/v1.0/

## Получение основных данных системы [/info]

### Запрос данных [GET]

+ Response 200 (application/json)

    + Body
    
            {
                "csrf": "<csrf code>"
            }


## Прямая авторизация пользователя [/auth]

### Запрос авторизации [POST]

+ Request (x-www-form-urlencoded)

            "username": "testuser",
            "password": "userpassword",
            "csrf": "<csrf code>"

+ Request (application/json)

        {
            "username": "testuser",
            "password": "userpassword",
            "csrf": "<csrf code>"
        }

+ Response  302 (text/plain)

    + Headers

            Location: /

## Авторизация через соцсети [/auth/:name?code=:code]

+ Parameters
    
    + name -- string, social network name (fb, vk)
    + code -- string, authorization code

### Запрос авторизации [GET]

+ Response  302 (text/plain)

    + Headers

            Location: /

