binding:
  port: 4000
  host: localhost

info:
  version: 1.0.0
  description: API SalesForMe
  vk_app: 5222884
  vk_api_version: "5.52"
  fb_app: 152750598427241
  google_app: 799617381412-qg9dbdsmtfr0aiui4o11btj0a368l3gh.apps.googleusercontent.com 
  mailru_app: 746248
  yandex_app: 04e8d72f9495458c80428a974ba18c3b

secrets:
  vk: 2KPSXWgZABSk4DmIdXkY
  facebook: d1bcfbf672e1f8ef9565c34f6a1ccaaa
  google: rICZWHSuk5VWYYJF8MWWSMU0

auth:
  google:
    #https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=799617381412-qg9dbdsmtfr0aiui4o11btj0a368l3gh.apps.googleusercontent.com&redirect_uri=http://salesforme.yaseek.ru/auth/google&scope=email
    client_id: 799617381412-qg9dbdsmtfr0aiui4o11btj0a368l3gh.apps.googleusercontent.com
    auth_uri: https://accounts.google.com/o/oauth2/auth 
    secret: rICZWHSuk5VWYYJF8MWWSMU0
  vk:
    client_id: 5222884
    api_version: "5.52"
    secret: 2KPSXWgZABSk4DmIdXkY
  facebook:
    client_id: 152750598427241
    secret: d1bcfbf672e1f8ef9565c34f6a1ccaaa
  mailru:
    client_id: 746248
    private_key: e14a2f71a54881adac117f36786cf29e
    secret: 4edce5668eaea0eacaebe9851040c07d
  yandex:
    client_id: 04e8d72f9495458c80428a974ba18c3b
    secret: b202d3c2f57b4bd0a3c89376b3636a08

mail:
#  host: smtp.yandex.ru
#  port: 25
#  secure: true
  service: Yandex
  auth:
    user: ab@izh.com
    pass: 84eEVCWB7v

admin:
  fromAddress: Системный администратор <ab@izh.com>

postgres:
  host: 185.26.115.63
  port: 5432
  database: sales4me
  user: postgres
  password: postgres
  connections: 10
  idleTimeout: 30000
  
session:
  secure_phrase: 6842f1a0-5427-11e6-8643-001e68746665
  expires: 86400 #seconds
  header: x-session-id

uploads:
  destination: /srv/uploads
  