binding:
  port: 4000
  host: localhost

info:
  version: 1.0.0
  description: API SalesForMe
  vk_app: 5222884

secrets:
  vk: 2KPSXWgZABSk4DmIdXkY
  facebook: 6789

postgres:
  host: 185.26.115.63
  port: 5432
  database: salesforme
  user: postgres
  password: postgres
  connections: 10
  idleTimeout: 30000
  
