binding:
  port: 4000
  host: localhost

info:
  version: 1.0.0
  description: API SalesForMe

postgres:
  server: 185.26.115.63
  port: 5432
  database: salesforme
  user: postgres
  password: postgres
